# Jekyll configuration

name: Ling@Concordia
description: Nil

url: "https://lingt.xyz"
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: '/jekyll-clean-dark'

social:
  github: lingt-xyz
  stackoverflow: 
  linkedin: 
  codepen: 
  instagram: 
  lastfm: 
  rss: feed.xml

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest:
  email: false

collections:
  notes:
    output: true

# Google Analytics key, leave blank to ignore
google_analytics_key: 
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrika: false

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 
comments: false

permalink: /:year/:month/:title/
gems: [jekyll-paginate]
paginate: 10

#highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['README.md', 'LICENSE', vendor]